appName: visual_relationship
logLevel: WARN

DEV:
  mongodb:
    url: mongodb://127.0.0.1:27017/visualRelations
    db: visualRelations
  namespace:
    dns: http://127.0.0.1:5000/
  cache:
    redis_url: redis://127.0.0.1:6379
    redis_host: 127.0.0.1
    redis_user: ""
    redis_port: 6379
    redis_password: ""
    ttl: 180
    max_size: 10000
  trained_models:
    object_detection:
      yolo:
        data_location: app/prediction_engine/trained_models/yolov3/data/
        weights_location: app/prediction_engine/trained_models/yolov3/weights/
        config_location: app/prediction_engine/trained_models/yolov3/cfg/
        model_weights: custom-yolov3-spp_final.weights
        model_config: custom-yolov3-spp.cfg
        model_labels: yolo_description.names
        relationship_labels: custom.names
      retinanet:
        data_location: ""
        weights_location: ""
        config_location: ""
        model_weights: ""
        model_config: ""
        model_labels: ""
    other_relations:
      model_location: app/prediction_engine/trained_models/other_relations/weights/
      model_architecture: model_architecture_200103.json
      model_weights: model_weights_200103.h5
      encoders:
        encoder_location: app/prediction_engine/trained_models/other_relations/weights/
        label_encoder: label_encoder.pkl
        relationship_encoder: relationship_encoder.pkl
    is_relations:
      model_location: app/prediction_engine/trained_models/is_relations/weights/
      data_location: app/prediction_engine/trained_models/is_relations/data/
      model_architecture: is_model_architecture_200124.json
      model_weights: is_model_weights_200124.h5
      relationship_labels: is_labels.names
      encoders:
        encoder_location: app/prediction_engine/trained_models/is_relations/weights/
        label_encoder: label_encoder.pkl
        attribute_encoder: revised_attribute_encoder.pkl

DEV:
  mongodb:
    url: mongodb://127.0.0.1:27017/visualRelations
    db: visualRelations
  namespace:
    dns: http://127.0.0.1:5000/
  cache:
    redis_url: redis://127.0.0.1:6379
    redis_host: 127.0.0.1
    redis_user: ""
    redis_port: 6379
    redis_password: ""
    ttl: 180
    max_size: 10000
  trained_models:
    object_detection:
      yolo:
        data_location: app/prediction_engine/trained_models/yolov3/data/
        weights_location: app/prediction_engine/trained_models/yolov3/weights/
        config_location: app/prediction_engine/trained_models/yolov3/cfg/
        model_weights: custom-yolov3-spp_final.weights
        model_config: custom-yolov3-spp.cfg
        model_labels: yolo_description.names
        relationship_labels: custom.names
      retinanet:
        data_location: ""
        weights_location: ""
        config_location: ""
        model_weights: ""
        model_config: ""
        model_labels: ""
    other_relations:
      model_location: app/prediction_engine/trained_models/other_relations/weights/
      model_architecture: model_architecture_200103.json
      model_weights: model_weights_200103.h5
      encoders:
        encoder_location: app/prediction_engine/trained_models/other_relations/weights/
        label_encoder: label_encoder.pkl
        relationship_encoder: relationship_encoder.pkl
    is_relations:
      model_location: app/prediction_engine/trained_models/is_relations/weights/
      data_location: app/prediction_engine/trained_models/is_relations/data/
      model_architecture: is_model_architecture_200124.json
      model_weights: is_model_weights_200124.h5
      relationship_labels: is_labels.names
      encoders:
        encoder_location: app/prediction_engine/trained_models/is_relations/weights/
        label_encoder: label_encoder.pkl
        attribute_encoder: revised_attribute_encoder.pkl

DEV:
  mongodb:
    url: mongodb://127.0.0.1:27017/visualRelations
    db: visualRelations
  namespace:
    dns: http://127.0.0.1:5000/
  cache:
    redis_url: redis://127.0.0.1:6379
    redis_host: 127.0.0.1
    redis_user: ""
    redis_port: 6379
    redis_password: ""
    ttl: 180
    max_size: 10000
  trained_models:
    object_detection:
      yolo:
        data_location: app/prediction_engine/trained_models/yolov3/data/
        weights_location: app/prediction_engine/trained_models/yolov3/weights/
        config_location: app/prediction_engine/trained_models/yolov3/cfg/
        model_weights: custom-yolov3-spp_final.weights
        model_config: custom-yolov3-spp.cfg
        model_labels: yolo_description.names
        relationship_labels: custom.names
      retinanet:
        data_location: ""
        weights_location: ""
        config_location: ""
        model_weights: ""
        model_config: ""
        model_labels: ""
    other_relations:
      model_location: app/prediction_engine/trained_models/other_relations/weights/
      model_architecture: model_architecture_200103.json
      model_weights: model_weights_200103.h5
      encoders:
        encoder_location: app/prediction_engine/trained_models/other_relations/weights/
        label_encoder: label_encoder.pkl
        relationship_encoder: relationship_encoder.pkl
    is_relations:
      model_location: app/prediction_engine/trained_models/is_relations/weights/
      data_location: app/prediction_engine/trained_models/is_relations/data/
      model_architecture: is_model_architecture_200124.json
      model_weights: is_model_weights_200124.h5
      relationship_labels: is_labels.names
      encoders:
        encoder_location: app/prediction_engine/trained_models/is_relations/weights/
        label_encoder: label_encoder.pkl
        attribute_encoder: revised_attribute_encoder.pkl
